add --vs option to configure script for building with visual studio (default to use Makefile)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -50,6 +50,9 @@ do
 		--xcode)
 		    echo "Will generate Xcode project"
 		    XCODE=1;;
+        --vs)
+            echo "Will generate Visual Studio .sln file"
+            VS="-tp vs";;
         --help | -h | --usage)
             echo "options include: --release, --tests, --xcode"
             exit;;
@@ -138,7 +141,7 @@ else
 
         *)
             #svn co svn+ssh://gimli.last.fm/svn/clientside/bin/win _bin
-            qmake -recursive Last.fm.pro "CONFIG -= flat" || die "Configure failed."
+            qmake -recursive $VS Last.fm.pro "CONFIG -= flat" || die "Configure failed."
             fix_sln
             BUILD_CMD='devenv /useenv Last.sln';;
     esac
