Adding a 64 bit build flag and fixing a 64 bit build problem.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -56,8 +56,11 @@ do
         --bundle)
             echo "Will force bundle generation"
             BUNDLE=1;;
+	--64bit)
+	    echo "Building 64bit specific version"
+	    SIXTYFOURBIT=1;;
         --help | -h | --usage)
-            echo "options include: --release, --tests, --xcode, --vs, --bundle"
+            echo "options include: --release, --tests, --xcode, --vs, --bundle, --64bit"
             exit;;
     esac
     
@@ -137,12 +140,17 @@ else
             fi
 
             if [ -d /Developer/Applications/Qt ] || [ $BUNDLE ]; then
-                configFlags='CONFIG -= release'
+                configFlags='CONFIG-=release'
             else
-                configFlags='CONFIG -= release app_bundle'
+                configFlags='CONFIG-=release app_bundle'
             fi
+	    
+	    if [ $SIXTYFOURBIT ]; then
+		configFlags="$configFlags CONFIG+=x86_64"
+	    fi
 
-            qmake -config debug -spec macx-g++ -recursive Last.fm.pro "$configFlags" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
+            $(echo qmake -config debug -spec macx-g++ -recursive Last.fm.pro "$configFlags" "$EXTRA_QMAKE_FLAGS") || die "Configure failed."
+            # qmake -config debug -spec macx-g++ -recursive Last.fm.pro "$configFlags" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
             BUILD_CMD='make'        
         fi;;
             
