iPod scrobbling now works on mac!

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -133,7 +133,13 @@ else
                 EXTRA_QMAKE_FLAGS='NOOP=""'
             fi
 
-            qmake -config debug -spec macx-g++ -recursive Last.fm.pro "CONFIG -= app_bundle release" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
+            if [ -d /Developer/Applications/Qt ]; then
+                configFlags='CONFIG -= release'
+            else
+                configFlags='CONFIG -= release app_bundle'
+            fi
+
+            qmake -config debug -spec macx-g++ -recursive Last.fm.pro "$configFlags" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
             BUILD_CMD='make'        
         fi;;
             
